### ISSUE TITLE
Rename Inbox to Messages

### ISSUE THREAD

**Issue by landry314** [lichess-org/lichobile#1075]
* Feature Request

Since the Inbox contains threaded conversations, it isn't really an Inbox, it is a Conversation List. It is an Inbox and Outbox and Archive. These days, the word Inbox isn't what it used to be when they were actually a collection of new messages and that is it.

I suggest "Messages". It is clearer to everyone that this is where your messages are: the ones you sent and received. Some people not as familiar with English might not know the word Inbox and if they don't have a version in their language they might be using the English version.

Anyway, I feel it is a more friendly word too. Messages are fun and social. An inbox is where your undone work goes on your office desk. It incites worry and annoyance. It is work. Messages are not work, they are connections to other players. It is a happy word.

**Comment by jas14** [comment]
@landry314 , thanks for the feedback. In order to provide as consistent an experience as possible across web and mobile, we're following the website's lead with regard to copy. The website still uses "inbox."

If you still feel this is an issue, please check out the [Lichess Discord](https://discord.com/invite/lichess) and the [server repository](https://github.com/lichess-org/lila) to see if someone's made a similar request and/or make make a suggestion.
