### ISSUE TITLE
Domain verification for opening links in app

### ISSUE THREAD

**Issue by jeeva2812** [lichess-org/lichobile#1457]
**Is your feature request related to a problem? Please describe.**
I am annoyed when someone sends me a game link or private tournament link in Mobile, it redirects to the web-based interface and not to the app,

**Describe the solution you'd like**
Not an expert, but I believe using Deep Links might resolve this issue. [Doc](https://developer.android.com/training/app-links)

**Describe alternatives you've considered**
Other alternatives might be a separate section in the app for games and tournaments using id.

**Additional context**
It would be a great addition but not an emergency request.

**Comment by michd** [comment]
Looking at [AndroidManifest.xml](https://github.com/lichess-org/lichobile/blob/6d54cfb14c8d85089f54c4115d15ba70481f90dd/android/app/src/main/AndroidManifest.xml#L36-L79) it looks like links are integrated into the app. However, as of Android 12, it is required to have domain verification opening http/https links in an app.

This entails adding a file called `/.well-known/assetlinks.json` to the root of the website (lichess.org) to verify that links for the domain lichess.org should indeed be opened by the app.

Here's an example such file that Youtube uses: https://youtube.com/.well-known/assetlinks.json

Here is the Android documentation on deep link verification: https://developer.android.com/training/app-links/verify-site-associations.

To be clear, to get these http/https links to open in the Android app from Android 12 onward, changes to the _website_ are required.

**Comment by jeeva2812** [comment]
Hello @michd 
Thanks for responding. I have checked, it works fine now. Closing the issue!

**Comment by michd** [comment]
Thanks @jeeva2812, but the reason I searched up this issue is because I found it to not be working on my device running Android 12.  :)

I've resolved the same issue in an app for my work, and can see that lichess.org does not serve [.well-known/assetlinks.json](https://lichess.org/.well-known/assetlinks.json) at this time (404s at the time of writing), which results in Android 12 and up not automatically verifying that the mobile app may indeed open http/https links pointing to lichess.org.

When I find some time I'll see if I can open up a pull request to to https://github.com/lichess-org/lila to add it. (If I'm able to get the signing key fingerprints of the app on Google Play)

**Comment by jeeva2812** [comment]
I am sorry, my bad, I misread the previous comment to be an issue in devices running lower than Android 12 and tested out in a Android 10 device. 

I will reopen the issue. If you are submitting a pull request or opening an issue in https://github.com/lichess-org/lila, please do link this issue so that I can close accordingly. Meanwhile I will also try if I can understand and add the necessary file :)

**Comment by michd** [comment]
Thank you, I'll make sure to link between the two issue/pull request if/when I get around to it. :)

**Comment by michd** [comment]
I have created a pull request addressing this: [lila issue #11062](https://github.com/lichess-org/lila/pull/11062)
