### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by jsinn-dev** [lichess-org/lichobile#1501]
**Describe the bug**
I get "error Failed at the lichobile@7.6.1 build script." when I execute `npm run build`

**To Reproduce**
1. Clone lichobile
2. Install Node.js
3. `cd lichobile`
3. `npm install`
4. `npm run build`

**Expected behavior**
I expect no error at build, and I expect an index.html to be generated inside the www folder.

**Screenshots**
https://pastebin.com/sPvMZV6p

**Smartphone :**
 - Device: Xiaomi Mi 8
 - OS: Android
 - Browser Duckduckgo

**Additional context**
A couple searches on the web hinted that it might be encoding issues, but I have UTF-8 so it should be fine.

**Comment by jas14** [comment]
Note: this appears to be on Windows Subsystem for Linux

**Comment by Dampfie93** [comment]
I get the same error compiling lichobile@7.7.1.

Android Studio
Windows

Is there a fix for it yet?

**Comment by Dampfie93** [comment]
Got it working for me.
Using the Current Version of Node instead of Latest Stable Current (LTS) made it possible to exec `npm run build`

**Comment by jas14** [comment]
There was no suggested version of the Node engine in [package.json at the time of the above comment](https://github.com/lichess-org/lichobile/blob/5fbaad94e7079d7e6bc6a65eebee6cd5499629ed/package.json) (Feb 4, 2021), but the "latest" version was 15.8.0. Since then, 16 LTS has been released, and is now advised in package.json. I'm going to close this issue assuming that the major version upgrade fixed it — please comment if not.
