### ISSUE TITLE
display on square screen

### ISSUE THREAD

**Issue by Brutosaure** [lichess-org/lichobile#1869]
**Describe the bug**
I got a new phone with a square screen : a Unihertz Titan (android 10)

Here is the display I get.
[Screenshot_20210929-221243](https://user-images.githubusercontent.com/91645413/135375205-7169c610-6650-40ad-9bfe-e5f51d5d3c27.png)

Lichess app is up to date.
I didnt find any way to reduce the size of the board in order to access the different shortcuts (like share, analyse and so on).
, whatever the menu is set on left or right in options, it still look like compressed.

Is this a display bug or did I miss something? Thanks

**Comment by alexpdp7** [comment]
I'm seeing this too (with a Titan Pocket, 716x720 screen resolution).

**Comment by veloce** [comment]
Sorry missed that one, hopefully should be good in next release.

**Comment by alexpdp7** [comment]
Hi @veloce , I'm https://lichess.org/@/koalillo on Lichess, and I donated 10€ due to this fix, as the repo points to https://lichess.org/patron as sponsorship. I know it's not a lot, but if you also want a more personal donation (e.g. charity of your choice, Paypal to you, etc.), I'm happy to pony up again.

(Note: I don't normally do this, but I suspect I may be the *only* Lichobile user using a square screen, so I feel obliged to say thank you in some way.)

**Comment by veloce** [comment]
I wasn't aware of square screen phones before to be honest, but considering this thread you are at least 2 users ;)
If you ever wish to donate again, you can continue to use lichess patron, thank you!
