### ISSUE TITLE
Make Switching On & Off Zen-Mode Easier On Phone

### ISSUE THREAD

**Issue by Fluffy-Cookie** [lichess-org/lichobile#2008]
### The Problem

Yeah, so it's quite hard to turn on and off the Zen -  Mode on mobile devices 
As of right now, we have to bring the slide menu (or whatever you call it) scroll till we reach settings, go to settings, select game display scroll down and enable\disable Zen - Mode. This is quite a lot of work if you just want a quick peek at your opponent or do something like that.

### A solution we'd like

Moving the zen mode option to the slide-out menu probably somewhere on the bottom. Any easy to access alternative is okay just one we figured out.

### Other alternatives could be 

A dedicated toggle switch near the board (while playing)

### Additional context

We had made a thread about this in the Lichess  Feedback forum [(Feature requests : make switching on and off zen mode easier on phone)](https://lichess.org/forum/lichess-feedback/feature-requests--make-switching-on-and-off-zen-mode-easier-on-phone) and in case you are picky about the user's opinion the post has 27+ likes and many positive replies

The so-called slide-out menu:

![Aj166Ad](https://user-images.githubusercontent.com/96821475/152491771-f782d4e6-484c-47ab-a60f-3bdb559d3f3c.png)

**Comment by jas14** [comment]
The website has put this as a menu item because I imagine it's not toggled very frequently, but it's still a top-level item. Reference screenshots for logged-out and logged-in users:
<img src="https://user-images.githubusercontent.com/569991/152646273-7bdd421b-f9cf-488d-a897-ad0ab0308457.png" width="350">
<img src="https://user-images.githubusercontent.com/569991/152646274-5b26509d-3066-4de4-a68a-259e466e4103.png" width="350">

**Comment by veloce** [comment]
You actually have a quick zen mode toggle from the game menu (bottom left button in game screen).
