### ISSUE TITLE
time goes more fast that my opponent

### ISSUE THREAD

**Issue by MarceloAsadelta** [lichess-org/lichobile#2107]
**Describe the bug**
I clearly that the opponnet time goes more slow that me in a app game. sometimes appear that the clock dont change immediately when i make a move. the problem goes on this game:

https://lichess.org/D5EIqRlE/white#90

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung A51]
 - OS: [Android 12 ]

**Additional context**

**Comment by jas14** [comment]
This is probably due to lag. At the time you filed this report, your clock would continue to count down between when you made a move and when the server acknowledged your move. That was changed in https://github.com/lichess-org/lichobile/pull/2014 (which first appeared in 7.15.0). Now, your clock will stop until the Lichess server acknowledges your move.

Ultimately, we can't do anything about poor network conditions, and there still may be a delay between when you make a move and when the server counts it, but hopefully the above makes this less confusing.
