### ISSUE TITLE
I can't promote my pawns... please solve this problem 

### ISSUE THREAD

**Issue by ibrahimyousef97** [lichess-org/lichobile#2217]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jas14** [comment]
@ibrahimyousef97 please fill out the issue template, which was provided so we could gather enough information to reproduce/isolate the issue.

**Comment by bertok56** [comment]
Me too...Hi, I'm writing because something a bit strange happens to me about the application for android. At the time of the promotion of the pawn appears a totally white stripe instead of the list of possible pieces (I know this because of the games played on the PC). Smartphone: - Xiaomi Redmi Note 5 - Android 9
![Screenshot_2022-10-16-20-39-59-725_org lichess mobileapp](https://user-images.githubusercontent.com/116115493/196526731-f81637e1-074d-4e8b-bcc6-31e273f53ce0.jpg)
![Screenshot_2022-10-16-20-35-07-365_org lichess mobileapp](https://user-images.githubusercontent.com/116115493/196526771-1b5a1ea1-1de9-4d00-b0f3-1412793f6ddb.jpg)
