### ISSUE TITLE
Time loss

### ISSUE THREAD

**Issue by MrHarryPottah** [lichess-org/lichobile#2465]
### What happened?

I have been losing time in hyper bullet and ultra bullet games from the last 1 weedk.I have checked my internet connection but that is very fast. I tried the same in 4 mobile devices but still I am facing the same issue. Please look into this asap. I have lost quite amount of hard earned rating due to tike losses. Basically it is showing me time getting lapsed in my opponents kitty but after around 2 seconds the time gets restored in the opponents time box and gets lapsed in mine. When this happens a couple of times in a game, it's impossible to cope up with it when you are playing tournaments. If action is not taken in appropriate time, you will lose a lichess user.

### How can we reproduce the bug?

I have no idea how you can do it

### Expected behavior

Please solve this 

### Device

Samsung M12..Samsung M34   Samsung A34

### Operating system

Android

### App version

V7.6.5

**Comment by jas14** [comment]
@MrHarryPottah , sounds like there is significant lag between you and the server. We changed the clock display so that the app won't show either clock running after you move until it receives confirmation from the server. See #2014.

This change made it into version 7.15.0. I see you're still on 7.6.5, so please upgrade to 7.15.0 or above.
