### ISSUE TITLE
The incorrect ban of players for issues on lichess server.  

### ISSUE THREAD

**Issue by MiV68** [lichess-org/lichobile#2492]
### What happened?

 I was disconnected from a game in the Lichess mobile app and received a 10-minute ban. However, the stated reasons for the ban did not occur. Repeatedly, when choosing a new game (2+1), a message briefly appeared at the bottom of the screen about issues on the Lichess server. Please investigate the algorithm for evaluating problematic player behavior. It seems unable to distinguish between server or connectivity issues and player behavior. In my case, such behavior did not occur. Otherwise, I support Lichess and appreciate the services provided to chess players.

### How can we reproduce the bug?

Unfortunately impossible. 

### Expected behavior

If there is issue on the server side instead players ban provide correct behavior and message. 

### Device

iPhone 15 Pro Max

### Operating system

iOS 17

### App version

8.0

**Comment by jas14** [comment]
@MiV68 sorry to hear that. This is the repository for the old mobile app, so I'm not sure we can help unless it's deemed that this was an issue directly caused by the mobile app.

I believe you can submit an appeal here if you believe your account was wrongly restricted or banned: https://lichess.org/appeal
